[project]
name = "django_robots_registry"
version = "0.3.1"
requires-python = ">=3.14.4"
dependencies = ["Django>=6.1.1"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.pyright]
typeCheckingMode = "strict"
venvPath = "."
venv = ".venv"

[tool.ruff]
line-length = 100
target-version = "py314"

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "DJ"]
